#!/bin/bash

echo "running yamllint against repository"
yamllint .

echo "running hadolint against Dockerfile"
hadolint Dockerfile

echo "running go test ./..."
# a bit of bash trickery to silence the output on success
output="$(go test ./...)"

if [[ $? -ne 0 ]] ; then
    echo "$output"
fi

